export { default as Hero } from './Hero/Hero';
export { default as Features } from './Features/Features'
export { default as HIW } from './HIW/Hiw';
export { default as About } from './About/About';
export { default as News } from './NewsLetter/News';
export { default as Testimonials } from './Testimonials/Testimonials';
export { default as FAQs } from './FAQs/FAQs';
export { default as Contact } from './Contact/Contact';
export { default as Footer } from './Footer/Footer';